apiVersion: v1
kind: Namespace
metadata:
  name: operator-ns ##Replace this with the name of you namespace.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-operator
  namespace: operator-ns ##Replace this with the name of you namespace.
  labels:
    app: frontend-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-operator
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend-operator
    spec:
      containers:
      - name: frontend-operator
        image: alismo1013/frontend-operator:latest
        ports:
        - containerPort: 80
        env:
        - name: BASE_URL
          value: "https://www.google.com"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-operator
  namespace: operator-ns ##Replace this with the name of you namespace.
spec:
  type: ClusterIP
  selector:
    app: frontend-operator
  ports:
    - port: 80
      targetPort: 80
